spring.application.name=fitmatch-mvc

spring.datasource.url=jdbc:postgresql://ep-jolly-math-aihgnats-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JmRYGBg2pU0M

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true